name: forcefields-dev
channels:
  - conda-forge
dependencies:
  - python >=3.9, <3.13
  - bump2version
  - foyer
  - pytest
  - pytest-cov
  - pre-commit
  - pip
  - gmso >= 0.9.0
  - pydantic >= 2
  - pip:
      - git+https://github.com/chrisjonesBSU/antefoyer.git@main 
