name: forcefields-dev
channels:
  - conda-forge
dependencies:
  - bump2version
  - codecov
  - foyer
  - pytest
  - pre-commit
  - pip
  - pydantic
  - lxml
  - pip:
      - "--editable=git+https://github.com/rsdefever/antefoyer.git#egg=antefoyer"
